# Generated by Django 2.2 on 2022-10-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_currency', '0005_auto_20210702_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradecurrency',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
    ]
