# Generated by Django 2.2 on 2022-10-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_currency', '0007_tradecurrency_type_currncy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradecurrency',
            name='chain_id',
            field=models.IntegerField(default=1650, verbose_name='Chain ID '),
        ),
    ]
