# Generated by Django 2.2 on 2024-01-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0002_adminuser_profile_pattern_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scheme_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Scheme Name')),
                ('Scheme_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Scheme Type')),
                ('Scheme_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Scheme Number')),
                ('Scheme_amount', models.CharField(blank=True, max_length=10, null=True, verbose_name='Scheme Amount')),
                ('Register_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Register Number')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'InActive')], default=0, verbose_name='Send Status')),
                ('Branch_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Branch Id')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheme',
                'db_table': 'SCHzWkaJsitsYeR',
            },
        ),
    ]
