# Generated by Django 2.2 on 2024-01-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0003_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='Scheme_type',
            field=models.IntegerField(choices=[(0, 'Amount'), (1, 'Weight')], default=0, verbose_name='Scheme Type'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'InActive')], default=0, verbose_name='Status'),
        ),
    ]
