# Generated by Django 2.2 on 2024-01-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0004_auto_20240107_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='Scheme_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Scheme Type'),
        ),
    ]
