# Generated by Django 2.2 on 2024-01-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0006_auto_20240107_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme_amount_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scheme_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Scheme Id')),
                ('Scheme_amount', models.CharField(blank=True, max_length=250, null=True, verbose_name='Scheme Amount')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'InActive')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheme Amount Master',
                'db_table': 'SCHAMTWkaJtsYeR',
            },
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='Scheme_amount',
        ),
    ]
