# Generated by Django 2.2 on 2024-01-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0007_auto_20240108_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='Scheme_amount',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Scheme Amount'),
        ),
        migrations.AddField(
            model_name='scheme_amount_master',
            name='user_count',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='User Count'),
        ),
    ]
