# Generated by Django 2.2 on 2024-01-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0009_scheme_amount_master_scheme_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metal_id', models.IntegerField(blank=True, null=True, verbose_name='Metal Id')),
                ('Metal_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Metal Name')),
                ('Metal_amount', models.CharField(blank=True, max_length=250, null=True, verbose_name='Metal Amount')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'InActive')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gold Master',
                'db_table': 'GOLjkghsiJtiuo',
            },
        ),
    ]
