# Generated by Django 2.2 on 2024-01-15 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='User Name')),
                ('Email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Email')),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')], verbose_name='Mobile Number')),
            ],
            options={
                'verbose_name': 'User Management',
                'db_table': 'USDQLUkJuU9TNt8m',
            },
        ),
        migrations.CreateModel(
            name='auth_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=250, null=True, verbose_name='Key')),
                ('user_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='User Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Userid', to='chit.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Auth Token',
                'db_table': 'TOKqeHWw3AZ8QWz',
            },
        ),
    ]
