# Generated by Django 2.2 on 2024-01-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_token',
        ),
    ]
