# Generated by Django 2.2 on 2024-01-15 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0002_delete_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_management',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
