# Generated by Django 2.2 on 2024-01-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0003_auto_20240115_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_otp', models.IntegerField(blank=True, null=True, verbose_name='Email Registration OTP')),
                ('phone_number_opt', models.IntegerField(blank=True, null=True, verbose_name='Phone Number Registration OTP')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_registration', to='chit.User_Management')),
            ],
            options={
                'verbose_name': 'OTP Registration',
                'db_table': 'OTPzTPzfNdmGTlER',
            },
        ),
    ]
