# Generated by Django 2.2 on 2024-01-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0004_otp_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(blank=True, null=True, verbose_name='User Individual Pin')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MPin', to='chit.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'M Pin',
                'db_table': 'MPINSWITHkpbdzR',
            },
        ),
    ]
