# Generated by Django 2.2 on 2024-01-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Gst_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Gst Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='pan_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Pan Number'),
        ),
    ]
