# Generated by Django 2.2 on 2022-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_auth', '0003_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='chainid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chain_id'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='wallet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wallet'),
        ),
    ]
