# Generated by Django 2.2 on 2022-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_auth', '0005_auto_20221103_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='select_token',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Select Token'),
        ),
    ]
